version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: shortenurl_app
    expose:
      - '8090'
    ports:
      - "8090:8090"
    command: node dist/index.js
    depends_on:
      - mongo
    environment:
      NODE_ENV: production
      MONGO_URI: "mongodb://mongo:27017/shortenurl-db"

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - "8083:8081"

volumes:
  data:
    driver: local
